# Cargo.toml

[workspace]
members = [
    "crates/ravel-cli",
    "crates/ravel-core",
    "crates/ravel-db-core",
    "crates/ravel-db-seaorm",
    "crates/ravel-http",
    "crates/ravel-generator",
    "crates/ravel-macros",
    "crates/ravel-support",
    "crates/ravel-test",
    "testblog"
]

resolver = "2"
