[package]
name = "testblog"
version = "0.1.0"
edition = "2024"

[dependencies]
ravel-core = { path = "../crates/ravel-core" }
ravel-facades = { path = "../crates/ravel-facades" }
ravel-http = { path = "../crates/ravel-http" }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
sea-orm = { version = "2.0.0-rc.40", features = [
    "sqlx-sqlite",
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }

[dev-dependencies]
ravel-test = { path = "../crates/ravel-test" }
