//! ravel db:seed — run database seeders.
//!
//! Delegates to the user project's `seed` binary via `cargo run --bin seed`.
//!
//! The `seed` binary is generated by `ravel new` at `src/bin/seed.rs`
//! and runs the seeders registered by the user.

use anyhow::Result;
use std::process::Command;

use super::utils::find_bin;

pub fn handle() -> Result<()> {
    let bin_name = find_bin("seed").ok_or_else(|| {
        anyhow::anyhow!(
            "No 'seed' binary found.\n\
             \n\
             Run `ravel new <name>` to create a project, or manually create\n\
             src/bin/seed.rs (see `ravel new` template)."
        )
    })?;

    let status = Command::new("cargo")
        .arg("run")
        .arg("--bin")
        .arg(&bin_name)
        .status()?;

    if !status.success() {
        anyhow::bail!("Seeding failed with exit code {:?}", status.code());
    }

    Ok(())
}
