//! ravel migrate — run / rollback migrations.
//!
//! These commands delegate to the user project's `migrate` binary via
//! `cargo run --bin migrate -- <subcommand> [steps]`.
//!
//! The `migrate` binary is generated by `ravel new` at `src/bin/migrate.rs`
//! and uses the Migrator registered in `database/migrations/mod.rs`.

use anyhow::Result;
use std::path::Path;
use std::process::Command;

/// Check whether a cargo bin target named `name` exists.
///
/// Looks for `src/bin/<name>.rs` or an explicit `[[bin]]` entry in Cargo.toml.
fn find_bin(name: &str) -> Option<String> {
    // 1. Check src/bin/name.rs
    let bin_path = format!("src/bin/{name}.rs");
    if Path::new(&bin_path).exists() {
        return Some(name.to_string());
    }

    // 2. Scan Cargo.toml for [[bin]] entries
    let cargo_path = Path::new("Cargo.toml");
    if !cargo_path.exists() {
        return None;
    }
    let content = std::fs::read_to_string(cargo_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        // Match patterns like: name = "migrate" or name = "migrate"
        if trimmed.starts_with("name = ") {
            if let Some(quoted) = trimmed.strip_prefix("name = \"") {
                if let Some(quoted_name) = quoted.strip_suffix('"') {
                    if quoted_name == name {
                        return Some(name.to_string());
                    }
                }
            }
        }
    }

    None
}

fn run_migrate(args: &[&str]) -> Result<()> {
    let bin_name = find_bin("migrate").ok_or_else(|| {
        anyhow::anyhow!(
            "No 'migrate' binary found.\n\
             \n\
             Run `ravel new <name>` to create a project, or manually create\n\
             src/bin/migrate.rs (see `ravel new` template)."
        )
    })?;

    let status = Command::new("cargo")
        .arg("run")
        .arg("--bin")
        .arg(&bin_name)
        .arg("--")
        .args(args)
        .status()?;

    if !status.success() {
        anyhow::bail!(
            "Migration command failed with exit code {:?}",
            status.code()
        );
    }

    Ok(())
}

pub async fn handle_migrate(steps: Option<u32>) -> Result<()> {
    let mut args = vec!["up"];
    let steps_str;
    if let Some(s) = steps {
        steps_str = s.to_string();
        args.push(&steps_str);
    }
    run_migrate(&args)
}

pub async fn handle_rollback(steps: Option<u32>) -> Result<()> {
    let mut args = vec!["down"];
    let steps_str;
    if let Some(s) = steps {
        steps_str = s.to_string();
        args.push(&steps_str);
    }
    run_migrate(&args)
}

pub async fn handle_refresh() -> Result<()> {
    run_migrate(&["refresh"])
}

pub async fn handle_fresh() -> Result<()> {
    run_migrate(&["fresh"])
}

pub async fn handle_status() -> Result<()> {
    run_migrate(&["status"])
}
