[package]
name = "ravel-http"
version = "0.1.0"
edition = "2024"
description = "HTTP layer for Ravel: route builder, server, middleware, session, auth, CSRF, rate limiting, file upload, validation"
license = "MIT"
repository = "https://github.com/jwwb681232/ravel"
homepage = "https://github.com/jwwb681232/ravel"
documentation = "https://docs.rs/ravel-http"
keywords = ["ravel", "http", "router", "middleware", "session"]
categories = ["web-programming::http-server", "web-programming"]
readme = "../../README.md"

[dependencies]
ravel-core = { path = "../ravel-core" }
ravel-error = { path = "../ravel-error" }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
axum = { workspace = true, features = ["multipart"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tera = { workspace = true }
regex = "1"
tower = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
hmac = "0.12"
sha2 = "0.10"
uuid = { workspace = true }
redis = { workspace = true, optional = true }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }

[[test]]
name = "session_redis"
required-features = ["redis"]
