/// Fills model fields from JSON data.
///
/// Auto-implemented by `#[derive(Model)]`.
/// The actual field-by-field fill logic is generated by the proc-macro.
pub trait Fillable: Sized {
    /// Set fields from a JSON object, returning the modified model.
    fn fill(self, data: serde_json::Value) -> Self;
}
