use sea_orm::{
    ConnectionTrait, DatabaseConnection,
    ExprTrait, Statement, Value,
};
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::collections::HashMap;

use crate::error::{RavelEloquentError, Result};
use crate::relations::{RelationKind, RelationMeta};

/// Model metadata — auto-implemented by #[derive(Model)]
pub trait ModelMeta {
    /// JSON-safe public type (hidden fields excluded)
    type Public: Serialize;

    /// Column metadata enum type
    type Columns: Copy;

    /// Database table name
    fn table_name() -> &'static str;

    /// All database column names (excluding relation fields)
    fn columns() -> &'static [&'static str];

    /// Primary key column name
    fn id_column() -> &'static str;

    /// Non-hidden column names (for API serialization)
    fn public_columns() -> &'static [&'static str];

    /// Relationship metadata. Empty by default — overridden by #[derive(Model)].
    fn relations() -> &'static [RelationMeta] {
        &[]
    }

    /// Column name for soft-delete timestamp. `None` means hard deletes only.
    fn soft_delete_column() -> Option<&'static str> {
        None
    }

    /// Look up a relationship by its field name.
    fn get_relation(name: &str) -> Option<&'static RelationMeta> {
        for rel in Self::relations() {
            if rel.field_name == name {
                return Some(rel);
            }
        }
        None
    }

    /// SeaORM Entity type (generated by macro)
    type Entity: sea_orm::EntityTrait;

    /// SeaORM ActiveModel type (generated by macro)
    type ActiveModel: sea_orm::ActiveModelTrait<Entity = Self::Entity> + Send;

    /// Locate a Column variant by column name string.
    fn find_column(_name: &str) -> Option<<Self::Entity as sea_orm::EntityTrait>::Column> {
        None
    }
}

// ── ModelExt ─────────────────────────────────────────────────────────────

/// Static CRUD operations for models.
///
/// Implemented automatically by `#[derive(Model)]`.
/// Uses SeaORM 2.0 native APIs for type-safe, cross-backend SQL generation.
#[async_trait::async_trait]
pub trait ModelExt: ModelMeta + DeserializeOwned + Serialize + Send + Sync + 'static {
    /// Find a record by its primary key.
    async fn find(db: &DatabaseConnection, id: impl Into<Value> + Send) -> Result<Option<Self>> {
        let id_val: Value = id.into();
        let backend = db.get_database_backend();
        let raw_sql = format!(
            "SELECT * FROM \"{}\" WHERE \"{}\" = $1{} LIMIT 1",
            Self::table_name(),
            Self::id_column(),
            match Self::soft_delete_column() {
                Some(del_col) => format!(" AND \"{}\" IS NULL", del_col),
                None => String::new(),
            },
        );
        let stmt = Statement::from_sql_and_values(backend, &raw_sql, [id_val]);
        let rows = db.query_all_raw(stmt).await.map_err(RavelEloquentError::Database)?;
        if let Some(row) = rows.into_iter().next() {
            crate::query::row_to_model(&row, Self::columns()).map(Some)
        } else {
            Ok(None)
        }
    }

    /// Find a record by its primary key, or return `RecordNotFound` error.
    async fn find_or_fail(db: &DatabaseConnection, id: impl Into<Value> + Send) -> Result<Self> {
        let id_val: Value = id.into();
        let id_str = format!("{:?}", id_val);
        Self::find(db, id_val)
            .await?
            .ok_or_else(|| RavelEloquentError::RecordNotFound {
                table: Self::table_name(),
                id: id_str,
            })
    }

    /// Fetch all records from the table.
    async fn all(db: &DatabaseConnection) -> Result<Vec<Self>> {
        let backend = db.get_database_backend();
        let sql = if let Some(del_col) = Self::soft_delete_column() {
            format!(
                "SELECT * FROM \"{}\" WHERE \"{}\" IS NULL",
                Self::table_name(),
                del_col,
            )
        } else {
            format!("SELECT * FROM \"{}\"", Self::table_name())
        };
        let rows = db
            .query_all_raw(Statement::from_string(backend, sql))
            .await
            .map_err(RavelEloquentError::Database)?;
        rows.into_iter()
            .map(|row| crate::query::row_to_model(&row, Self::columns()))
            .collect()
    }

    /// Fetch all records (including soft-deleted).
    async fn all_with_trashed(db: &DatabaseConnection) -> Result<Vec<Self>> {
        let sql = format!("SELECT * FROM \"{}\"", Self::table_name());
        let rows = db
            .query_all_raw(Statement::from_string(db.get_database_backend(), sql))
            .await
            .map_err(RavelEloquentError::Database)?;
        rows.into_iter()
            .map(|row| crate::query::row_to_model(&row, Self::columns()))
            .collect()
    }

    /// Fetch only soft-deleted records.
    async fn all_only_trashed(db: &DatabaseConnection) -> Result<Vec<Self>> {
        let del_col = Self::soft_delete_column().ok_or_else(|| {
            RavelEloquentError::Other("Soft deletes not enabled on this model".into())
        })?;
        let sql = format!(
            "SELECT * FROM \"{}\" WHERE \"{}\" IS NOT NULL",
            Self::table_name(),
            del_col,
        );
        let rows = db
            .query_all_raw(Statement::from_string(db.get_database_backend(), sql))
            .await
            .map_err(RavelEloquentError::Database)?;
        rows.into_iter()
            .map(|row| crate::query::row_to_model(&row, Self::columns()))
            .collect()
    }

    /// Fetch all records with eager-loaded relations.
    async fn all_with(db: &DatabaseConnection, relations: &[&str]) -> Result<Vec<Self>> {
        let mut items = Self::all(db).await?;
        for rel in relations {
            Self::load_relation(rel, &mut items, db).await?;
        }
        Ok(items)
    }

    /// Eager-load a single relation onto already-fetched model instances.
    async fn load_relation(
        rel: &str,
        items: &mut Vec<Self>,
        db: &DatabaseConnection,
    ) -> Result<()> {
        let meta = Self::get_relation(rel).ok_or_else(|| {
            RavelEloquentError::Other(format!(
                "Relation '{}' not found on {}",
                rel,
                Self::table_name()
            ).into())
        })?;

        // BelongsToMany: pivot table → related table → group
        if meta.kind == RelationKind::BelongsToMany {
            return Self::load_belongs_to_many(meta, items, db).await;
        }

        let columns = (meta.get_columns)();

        // Collect local-key values from the parent models.
        let ids: Vec<String> = items
            .iter()
            .map(|item| -> Result<String> {
                let json = serde_json::to_value(item)?;
                let id_val = json.get(meta.local_key).ok_or_else(|| {
                    RavelEloquentError::Other(format!(
                        "Key '{}' not found in serialized model",
                        meta.local_key
                    ).into())
                })?;
                Ok(match id_val {
                    serde_json::Value::Number(n) => n.to_string(),
                    serde_json::Value::String(s) => s.clone(),
                    serde_json::Value::Bool(b) => b.to_string(),
                    _ => id_val.to_string(),
                })
            })
            .collect::<Result<Vec<_>>>()?;

        if ids.is_empty() {
            return Ok(());
        }

        let values: Vec<sea_orm::Value> = ids
            .iter()
            .map(|id| {
                id.parse::<i64>()
                    .map(|i| sea_orm::Value::BigInt(Some(i)))
                    .unwrap_or_else(|_| sea_orm::Value::String(Some(id.clone())))
            })
            .collect();

        let sea_values: Vec<sea_orm::sea_query::Value> =
            values.into_iter().map(|v| v.into()).collect();

        let mut select = sea_orm::sea_query::Query::select();
        select.from(sea_orm::sea_query::Alias::new(meta.table_name));
        for col in columns {
            select.column(sea_orm::sea_query::Alias::new(*col));
        }
        select.and_where(
            sea_orm::sea_query::Expr::col(sea_orm::sea_query::Alias::new(meta.foreign_key))
                .is_in(sea_values),
        );

        let sql = match db.get_database_backend() {
            sea_orm::DbBackend::MySql => {
                select.to_string(sea_orm::sea_query::MysqlQueryBuilder)
            }
            sea_orm::DbBackend::Postgres => {
                select.to_string(sea_orm::sea_query::PostgresQueryBuilder)
            }
            sea_orm::DbBackend::Sqlite => {
                select.to_string(sea_orm::sea_query::SqliteQueryBuilder)
            }
            _ => select.to_string(sea_orm::sea_query::SqliteQueryBuilder),
        };

        #[cfg(test)]
        eprintln!("[ravel-eloquent] eager-load SQL: {}", sql);

        let stmt = sea_orm::Statement::from_string(db.get_database_backend(), sql);
        let rows = db
            .query_all_raw(stmt)
            .await
            .map_err(RavelEloquentError::Database)?;

        // Group related rows by their foreign key.
        let mut grouped: HashMap<String, Vec<serde_json::Map<String, serde_json::Value>>> =
            HashMap::new();
        for row in rows {
            let mut map = serde_json::Map::new();
            for (i, col_name) in columns.iter().enumerate() {
                let val = crate::query::try_extract(&row, i);
                map.insert(col_name.to_string(), val);
            }
            let fk_val = map.get(meta.foreign_key).ok_or_else(|| {
                RavelEloquentError::Other(format!(
                    "Foreign key '{}' not found in related row",
                    meta.foreign_key,
                ).into())
            })?;
            let fk = match fk_val {
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::String(s) => s.clone(),
                _ => fk_val.to_string(),
            };
            grouped.entry(fk).or_default().push(map);
        }

        // Inject grouped data back into the parent JSON values.
        let mut json_values: Vec<serde_json::Value> = items
            .iter()
            .map(|i| serde_json::to_value(i))
            .collect::<std::result::Result<Vec<_>, _>>()?;
        for val in &mut json_values {
            let id_val = val.get(meta.local_key).ok_or_else(|| {
                RavelEloquentError::Other(format!(
                    "Local key '{}' not found in serialized parent model",
                    meta.local_key
                ).into())
            })?;
            let id = match id_val {
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::String(s) => s.clone(),
                _ => id_val.to_string(),
            };
            if let Some(rel_items) = grouped.get(&id) {
                match meta.kind {
                    RelationKind::HasMany => {
                        val[rel] = serde_json::to_value(rel_items)?;
                    }
                    RelationKind::HasOne | RelationKind::BelongsTo | RelationKind::BelongsToMany => {
                        val[rel] = serde_json::to_value(rel_items.first().ok_or_else(|| {
                            RavelEloquentError::Other("Empty relation group for HasOne/BelongsTo".into())
                        })?)?;
                    }
                }
            }
        }

        // Re-deserialise into the parent model.
        let new_items: Vec<Self> = json_values
            .iter()
            .map(|v| serde_json::from_value(v.clone()))
            .collect::<std::result::Result<Vec<_>, _>>()?;
        *items = new_items;

        Ok(())
    }

    /// Create a new record from JSON data and return it.
    async fn create(data: serde_json::Value, db: &DatabaseConnection) -> Result<Self> {
        let backend = db.get_database_backend();
        let cols: Vec<String> = Self::columns()
            .iter()
            .map(|c| format!("\"{}\"", c))
            .collect();
        let values: Vec<Value> = Self::columns()
            .iter()
            .map(|c| {
                data.get(c)
                    .map(json_val_to_sea_value)
                    .unwrap_or(Value::BigInt(None))
            })
            .collect();

        let placeholders: Vec<String> = (1..=values.len())
            .map(|i| format!("${}", i))
            .collect();

        match backend {
            sea_orm::DbBackend::MySql => {
                // MySQL does not support RETURNING — insert first, then
                // resolve the primary key via LAST_INSERT_ID or the
                // caller-supplied value, and fetch the row.
                let sql = format!(
                    "INSERT INTO \"{}\" ({}) VALUES ({})",
                    Self::table_name(),
                    cols.join(", "),
                    placeholders.join(", "),
                );
                let stmt = Statement::from_sql_and_values(backend, &sql, values);
                let result = db
                    .execute(&StmtExec(stmt))
                    .await
                    .map_err(RavelEloquentError::Database)?;

                let id_col = Self::id_column();
                let auto_id = result.last_insert_id();
                let fetch_id = if auto_id > 0 {
                    Value::BigInt(Some(auto_id as i64))
                } else {
                    json_val_to_sea_value(data.get(id_col).ok_or_else(|| {
                        RavelEloquentError::Other(format!(
                            "Primary key '{id_col}' not found in insert data and no auto-increment id returned",
                        ).into())
                    })?)
                };

                Self::find(db, fetch_id)
                    .await?
                    .ok_or_else(|| RavelEloquentError::Other("INSERT succeeded but row not found on fetch-back".into()))
            }
            _ => {
                // PostgreSQL and SQLite (3.35+) support RETURNING.
                let sql = format!(
                    "INSERT INTO \"{}\" ({}) VALUES ({}) RETURNING *",
                    Self::table_name(),
                    cols.join(", "),
                    placeholders.join(", "),
                );
                let stmt = Statement::from_sql_and_values(backend, &sql, values);
                let rows = db
                    .query_all_raw(stmt)
                    .await
                    .map_err(RavelEloquentError::Database)?;
                crate::query::row_to_model(
                    &rows
                        .into_iter()
                        .next()
                        .ok_or_else(|| RavelEloquentError::Other("INSERT returned no rows".into()))?,
                    Self::columns(),
                )
            }
        }
    }

    /// Delete records by their primary key(s). Supports soft deletes.
    async fn destroy(db: &DatabaseConnection, ids: impl IntoIterator<Item = impl Into<Value>> + Send) -> Result<u64> {
        let id_values: Vec<Value> = ids.into_iter().map(|id| id.into()).collect();
        if id_values.is_empty() {
            return Ok(0);
        }
        let pk_col = Self::id_column();
        let placeholders: Vec<String> = (1..=id_values.len())
            .map(|i| format!("${}", i))
            .collect();
        let sql = if let Some(del_col) = Self::soft_delete_column() {
            format!(
                "UPDATE \"{}\" SET \"{}\" = CURRENT_TIMESTAMP WHERE \"{}\" IN ({})",
                Self::table_name(),
                del_col,
                pk_col,
                placeholders.join(", "),
            )
        } else {
            format!(
                "DELETE FROM \"{}\" WHERE \"{}\" IN ({})",
                Self::table_name(),
                pk_col,
                placeholders.join(", "),
            )
        };
        let backend = db.get_database_backend();
        let stmt = Statement::from_sql_and_values(backend, &sql, id_values);
        let result = db.execute(&StmtExec(stmt)).await.map_err(RavelEloquentError::Database)?;
        Ok(result.rows_affected())
    }

    // ── BelongsToMany helpers ──────────────────────────────────────────

    /// Eager-load a BelongsToMany relation via a pivot table.
    async fn load_belongs_to_many(
        meta: &RelationMeta,
        items: &mut Vec<Self>,
        db: &DatabaseConnection,
    ) -> Result<()> {
        let columns = (meta.get_columns)();
        let pivot_table = meta.pivot_table.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_table".into())
        })?;
        let pivot_fk = meta.pivot_foreign_key.unwrap_or(meta.foreign_key);
        let pivot_rk = meta.pivot_related_key.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_related_key".into())
        })?;

        // Collect local-key values from the parent models.
        let ids: Vec<String> = items
            .iter()
            .map(|item| -> Result<String> {
                let json = serde_json::to_value(item)?;
                let id_val = json.get(meta.local_key).ok_or_else(|| {
                    RavelEloquentError::Other(format!(
                        "Key '{}' not found in serialized model",
                        meta.local_key
                    ).into())
                })?;
                Ok(match id_val {
                    serde_json::Value::Number(n) => n.to_string(),
                    serde_json::Value::String(s) => s.clone(),
                    serde_json::Value::Bool(b) => b.to_string(),
                    _ => id_val.to_string(),
                })
            })
            .collect::<Result<Vec<_>>>()?;

        if ids.is_empty() {
            return Ok(());
        }

        let in_vals: Vec<Value> = ids
            .iter()
            .map(|id| {
                id.parse::<i64>()
                    .map(|i| Value::BigInt(Some(i)))
                    .unwrap_or_else(|_| Value::String(Some(id.clone().into())))
            })
            .collect();
        let pivot_placeholders: Vec<String> = (1..=in_vals.len())
            .map(|i| format!("${}", i))
            .collect();

        // Step 1: query the pivot table for (parent_id, related_id) pairs.
        let pivot_sql = format!(
            "SELECT \"{}\", \"{}\" FROM \"{}\" WHERE \"{}\" IN ({})",
            pivot_fk, pivot_rk, pivot_table, pivot_fk, pivot_placeholders.join(", ")
        );
        let pivot_stmt = Statement::from_sql_and_values(db.get_database_backend(), &pivot_sql, in_vals.clone());
        let pivot_rows = db
            .query_all_raw(pivot_stmt)
            .await
            .map_err(RavelEloquentError::Database)?;

        // Map: parent_id → Vec<related_id>
        let mut pivot_map: HashMap<String, Vec<String>> = HashMap::new();
        let mut all_related_ids: Vec<String> = Vec::new();
        for row in &pivot_rows {
            let parent_id = crate::query::try_extract(row, 0).to_string();
            let related_id = crate::query::try_extract(row, 1).to_string();
            let clean_pid = parent_id.trim_matches('"');
            let clean_rid = related_id.trim_matches('"');
            pivot_map.entry(clean_pid.to_string()).or_default().push(clean_rid.to_string());
            all_related_ids.push(clean_rid.to_string());
        }

        if all_related_ids.is_empty() {
            let mut json_values: Vec<serde_json::Value> = items
                .iter()
                .map(|i| serde_json::to_value(i))
                .collect::<std::result::Result<Vec<_>, _>>()?;
            let rel_name = meta.field_name;
            for val in &mut json_values {
                val[rel_name] = serde_json::to_value(Vec::<serde_json::Value>::new())?;
            }
            let new_items: Vec<Self> = json_values
                .iter()
                .map(|v| serde_json::from_value(v.clone()))
                .collect::<std::result::Result<Vec<_>, _>>()?;
            *items = new_items;
            return Ok(());
        }

        // Step 2: query the related table for all related records.
        let rk_values: Vec<Value> = all_related_ids
            .iter()
            .map(|id| {
                id.parse::<i64>()
                    .map(|i| Value::BigInt(Some(i)))
                    .unwrap_or_else(|_| Value::String(Some(id.clone().into())))
            })
            .collect();
        let rk_placeholders: Vec<String> = (1..=rk_values.len())
            .map(|i| format!("${}", i))
            .collect();
        let related_pk_col = columns.first().unwrap_or(&"id");
        let related_sql = format!(
            "SELECT * FROM \"{}\" WHERE \"{}\" IN ({})",
            meta.table_name, related_pk_col, rk_placeholders.join(", ")
        );
        let related_stmt = Statement::from_sql_and_values(db.get_database_backend(), &related_sql, rk_values);
        let related_rows = db
            .query_all_raw(related_stmt)
            .await
            .map_err(RavelEloquentError::Database)?;

        // Index: related_id → JSON value
        let mut related_map: HashMap<String, serde_json::Value> = HashMap::new();
        for row in &related_rows {
            let mut map = serde_json::Map::new();
            for (i, col_name) in columns.iter().enumerate() {
                let val = crate::query::try_extract(&row, i);
                map.insert(col_name.to_string(), val);
            }
            let rid_val = map.get(*related_pk_col).ok_or_else(|| {
                RavelEloquentError::Other(format!(
                    "Primary key '{}' not found in related row",
                    related_pk_col,
                ).into())
            })?;
            let rid = match rid_val {
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            related_map.insert(rid, serde_json::Value::Object(map));
        }

        // Step 3: group by parent, injecting into the JSON values.
        let mut json_values: Vec<serde_json::Value> = items
            .iter()
            .map(|i| serde_json::to_value(i))
            .collect::<std::result::Result<Vec<_>, _>>()?;
        let rel_name = meta.field_name;
        for val in &mut json_values {
            let pid_val = val.get(meta.local_key).ok_or_else(|| {
                RavelEloquentError::Other(format!(
                    "Local key '{}' not found in serialized parent model",
                    meta.local_key
                ).into())
            })?;
            let pid = match pid_val {
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            let rel_items: Vec<serde_json::Value> = pivot_map
                .get(&pid)
                .map(|rids| {
                    rids.iter()
                        .filter_map(|rid| related_map.get(rid).cloned())
                        .collect()
                })
                .unwrap_or_default();
            val[rel_name] = serde_json::to_value(rel_items)?;
        }

        let new_items: Vec<Self> = json_values
            .iter()
            .map(|v| serde_json::from_value(v.clone()))
            .collect::<std::result::Result<Vec<_>, _>>()?;
        *items = new_items;

        Ok(())
    }

    // ── Pivot table operations (BelongsToMany) ─────────────────────────

    /// Attach related IDs to a BelongsToMany relation via the pivot table.
    async fn attach(
        &self,
        rel_name: &str,
        related_ids: &[impl Into<Value> + Clone + Send + Sync],
        db: &DatabaseConnection,
    ) -> Result<()> {
        let meta = Self::get_relation(rel_name).ok_or_else(|| {
            RavelEloquentError::Other(format!("Relation '{rel_name}' not found").into())
        })?;
        if meta.kind != RelationKind::BelongsToMany {
            return Err(RavelEloquentError::Other("attach() requires a BelongsToMany relation".into()));
        }
        let pivot_table = meta.pivot_table.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_table".into())
        })?;
        let pivot_fk = meta.pivot_foreign_key.unwrap_or(meta.foreign_key);
        let pivot_rk = meta.pivot_related_key.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_related_key".into())
        })?;

        let data = serde_json::to_value(self)?;
        let parent_id_val = json_val_to_sea_value(data.get(meta.local_key).ok_or_else(|| {
            RavelEloquentError::Other(format!(
                "Local key '{}' not found — model may be missing the pk field",
                meta.local_key,
            ).into())
        })?);

        let backend = db.get_database_backend();
        for rid in related_ids {
            let sql = format!(
                "INSERT OR IGNORE INTO \"{}\" (\"{}\", \"{}\") VALUES ($1, $2)",
                pivot_table, pivot_fk, pivot_rk
            );
            let stmt = Statement::from_sql_and_values(
                backend, &sql,
                [parent_id_val.clone(), rid.clone().into()],
            );
            db.execute(&StmtExec(stmt))
                .await
                .map_err(RavelEloquentError::Database)?;
        }
        Ok(())
    }

    /// Detach related IDs from a BelongsToMany relation via the pivot table.
    async fn detach(
        &self,
        rel_name: &str,
        related_ids: &[impl Into<Value> + Clone + Send + Sync],
        db: &DatabaseConnection,
    ) -> Result<u64> {
        let meta = Self::get_relation(rel_name).ok_or_else(|| {
            RavelEloquentError::Other(format!("Relation '{rel_name}' not found").into())
        })?;
        if meta.kind != RelationKind::BelongsToMany {
            return Err(RavelEloquentError::Other("detach() requires a BelongsToMany relation".into()));
        }
        let pivot_table = meta.pivot_table.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_table".into())
        })?;
        let pivot_fk = meta.pivot_foreign_key.unwrap_or(meta.foreign_key);
        let pivot_rk = meta.pivot_related_key.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_related_key".into())
        })?;
        let data = serde_json::to_value(self)?;
        let parent_id_val = json_val_to_sea_value(data.get(meta.local_key).ok_or_else(|| {
            RavelEloquentError::Other(format!(
                "Local key '{}' not found — model may be missing the pk field",
                meta.local_key,
            ).into())
        })?);

        let relate_values: Vec<Value> = related_ids
            .iter()
            .map(|id| id.clone().into())
            .collect();
        if relate_values.is_empty() {
            return Ok(0);
        }

        let rk_placeholders: Vec<String> = (2..=relate_values.len() + 1)
            .map(|i| format!("${}", i))
            .collect();
        let sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = $1 AND \"{}\" IN ({})",
            pivot_table, pivot_fk, pivot_rk, rk_placeholders.join(", "),
        );

        let mut all_values: Vec<Value> = vec![parent_id_val];
        all_values.extend(relate_values);

        let backend = db.get_database_backend();
        let stmt = Statement::from_sql_and_values(backend, &sql, all_values);
        let result = db.execute(&StmtExec(stmt)).await.map_err(RavelEloquentError::Database)?;
        Ok(result.rows_affected())
    }

    /// Sync related IDs for a BelongsToMany relation (detach all, then attach the given set).
    async fn sync(
        &self,
        rel_name: &str,
        related_ids: &[impl Into<Value> + Clone + Send + Sync],
        db: &DatabaseConnection,
    ) -> Result<()> {
        let meta = Self::get_relation(rel_name).ok_or_else(|| {
            RavelEloquentError::Other(format!("Relation '{rel_name}' not found").into())
        })?;
        if meta.kind != RelationKind::BelongsToMany {
            return Err(RavelEloquentError::Other("sync() requires a BelongsToMany relation".into()));
        }
        let pivot_table = meta.pivot_table.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_table".into())
        })?;
        let data = serde_json::to_value(self)?;
        let pivot_fk = meta.pivot_foreign_key.unwrap_or(meta.foreign_key);
        let pivot_rk = meta.pivot_related_key.ok_or_else(|| {
            RavelEloquentError::Other("BelongsToMany requires pivot_related_key".into())
        })?;
        let parent_id_val = json_val_to_sea_value(data.get(meta.local_key).ok_or_else(|| {
            RavelEloquentError::Other(format!(
                "Local key '{}' not found — model may be missing the pk field",
                meta.local_key,
            ).into())
        })?);
        let backend = db.get_database_backend();

        // Delete all existing pivot rows for this parent.
        let del_sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = $1",
            pivot_table, pivot_fk,
        );
        let del_stmt = Statement::from_sql_and_values(
            backend, &del_sql, [parent_id_val.clone()]);
        db.execute(&StmtExec(del_stmt)).await.map_err(RavelEloquentError::Database)?;

        // Insert new pivots.
        for rid in related_ids {
            let ins_sql = format!(
                "INSERT INTO \"{}\" (\"{}\", \"{}\") VALUES ($1, $2)",
                pivot_table, pivot_fk, pivot_rk
            );
            let ins_stmt = Statement::from_sql_and_values(
                backend, &ins_sql,
                [parent_id_val.clone(), rid.clone().into()],
            );
            db.execute(&StmtExec(ins_stmt))
                .await
                .map_err(RavelEloquentError::Database)?;
        }
        Ok(())
    }
}

// ── ActiveModelExt ───────────────────────────────────────────────────────

/// Consumptive write operations — auto-implemented by #[derive(Model)].
#[async_trait::async_trait]
pub trait ActiveModelExt: ModelExt {
    /// Persist the model: INSERT if id is 0/null, UPDATE otherwise.
    /// Returns the back-filled instance.
    async fn save(self, db: &DatabaseConnection) -> Result<Self> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let is_new = data
            .get(id_col)
            .map(|v| v.is_null() || v.as_i64() == Some(0))
            .unwrap_or(true);

        if is_new {
            let mut data = data;
            if let Some(obj) = data.as_object_mut() {
                obj.remove(id_col);
            }
            Self::create(data, db).await
        } else {
            let cols: Vec<&&str> = Self::columns()
                .iter()
                .filter(|c| **c != id_col)
                .collect();
            let pairs: Vec<(&str, Value)> = cols
                .iter()
                .filter_map(|c| {
                    data.get(**c).map(|v| (**c, json_val_to_sea_value(v)))
                })
                .collect();

            if pairs.is_empty() {
                return Ok(self);
            }

            let set_clauses: Vec<String> = pairs.iter()
                .enumerate()
                .map(|(i, (col, _))| format!("\"{}\" = ${}", col, i + 1))
                .collect();

            let id_val = data.get(id_col).ok_or_else(|| {
                RavelEloquentError::Other(format!(
                    "Primary key '{}' not found in serialized model data",
                    id_col,
                ).into())
            })?;
            let id_sea_val = json_val_to_sea_value(id_val);
            let id_placeholder = format!("${}", pairs.len() + 1);

            let sql = format!(
                "UPDATE \"{}\" SET {} WHERE \"{}\" = {}",
                Self::table_name(),
                set_clauses.join(", "),
                id_col,
                id_placeholder,
            );

            let mut all_values: Vec<Value> = pairs.into_iter().map(|(_, v)| v).collect();
            all_values.push(id_sea_val);

            let stmt = Statement::from_sql_and_values(db.get_database_backend(), &sql, all_values);
            db.execute(&StmtExec(stmt))
                .await
                .map_err(RavelEloquentError::Database)?;

            let id_for_fetch = json_val_to_sea_value(id_val);
            Self::find(db, id_for_fetch)
                .await?
                .ok_or_else(|| RavelEloquentError::RecordNotFound {
                    table: Self::table_name(),
                    id: id_val.to_string(),
                })
        }
    }

    /// Force INSERT regardless of id value.
    async fn insert(self, db: &DatabaseConnection) -> Result<Self> {
        Self::create(serde_json::to_value(&self)?, db).await
    }

    /// Force UPDATE. Returns `UpdateWithoutId` error if id is 0/null.
    async fn update(self, db: &DatabaseConnection) -> Result<Self> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let is_empty = data
            .get(id_col)
            .map(|v| v.is_null() || v.as_i64() == Some(0))
            .unwrap_or(true);

        if is_empty {
            return Err(RavelEloquentError::UpdateWithoutId);
        }
        self.save(db).await
    }

    /// DELETE the row. Consumes self.
    /// If soft deletes are enabled, sets `deleted_at = CURRENT_TIMESTAMP` instead.
    /// Use `force_delete()` to bypass soft delete.
    async fn delete(self, db: &DatabaseConnection) -> Result<()> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let id_val = data
            .get(id_col)
            .ok_or_else(|| RavelEloquentError::Other("Cannot delete: missing id".into()))?;
        let id_sea_val = json_val_to_sea_value(id_val);

        if let Some(del_col) = Self::soft_delete_column() {
            let sql = format!(
                "UPDATE \"{}\" SET \"{}\" = CURRENT_TIMESTAMP WHERE \"{}\" = $1",
                Self::table_name(),
                del_col,
                id_col,
            );
            let stmt = Statement::from_sql_and_values(
                db.get_database_backend(), &sql, [id_sea_val]);
            db.execute(&StmtExec(stmt))
                .await
                .map_err(RavelEloquentError::Database)?;
        } else {
            let sql = format!(
                "DELETE FROM \"{}\" WHERE \"{}\" = $1",
                Self::table_name(),
                id_col,
            );
            let stmt = Statement::from_sql_and_values(
                db.get_database_backend(), &sql, [id_sea_val]);
            db.execute(&StmtExec(stmt))
                .await
                .map_err(RavelEloquentError::Database)?;
        }
        Ok(())
    }

    /// Hard-delete the row, bypassing soft deletes.
    async fn force_delete(self, db: &DatabaseConnection) -> Result<()> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let id_val = data
            .get(id_col)
            .ok_or_else(|| RavelEloquentError::Other("Cannot force delete: missing id".into()))?;
        let id_sea_val = json_val_to_sea_value(id_val);

        let sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = $1",
            Self::table_name(),
            id_col,
        );
        let stmt = Statement::from_sql_and_values(
            db.get_database_backend(), &sql, [id_sea_val]);
        db.execute(&StmtExec(stmt))
            .await
            .map_err(RavelEloquentError::Database)?;
        Ok(())
    }

    /// Restore a soft-deleted record (sets `deleted_at = NULL`).
    async fn restore(self, db: &DatabaseConnection) -> Result<Self> {
        let del_col = Self::soft_delete_column().ok_or_else(|| {
            RavelEloquentError::Other("Soft deletes not enabled on this model".into())
        })?;
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let id_val = data
            .get(id_col)
            .ok_or_else(|| RavelEloquentError::Other("Cannot restore: missing id".into()))?;
        let id_sea_val = json_val_to_sea_value(id_val);

        let sql = format!(
            "UPDATE \"{}\" SET \"{}\" = NULL WHERE \"{}\" = $1",
            Self::table_name(),
            del_col,
            id_col,
        );
        let stmt = Statement::from_sql_and_values(
            db.get_database_backend(), &sql, [id_sea_val]);
        db.execute(&StmtExec(stmt))
            .await
            .map_err(RavelEloquentError::Database)?;

        let id_for_fetch = json_val_to_sea_value(id_val);
        Self::find(db, id_for_fetch)
            .await?
            .ok_or_else(|| RavelEloquentError::RecordNotFound {
                table: Self::table_name(),
                id: id_val.to_string(),
            })
    }

    /// Re-fetch the record from the database by id.
    async fn refresh(self, db: &DatabaseConnection) -> Result<Self> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let id_val = data
            .get(id_col)
            .ok_or_else(|| RavelEloquentError::Other("Cannot refresh: missing id".into()))?;

        let id_for_fetch = json_val_to_sea_value(id_val);
        Self::find(db, id_for_fetch)
            .await?
            .ok_or_else(|| RavelEloquentError::RecordNotFound {
                table: Self::table_name(),
                id: id_val.to_string(),
            })
    }
}

// ── Replicates ───────────────────────────────────────────────────────────

/// Clone a model instance — useful for creating a copy to persist.
pub trait Replicates: Clone + ModelMeta {
    /// Create a replica (deep copy) of this model.
    fn replicate(&self) -> Self {
        self.clone()
    }
}

// ── Serializes ───────────────────────────────────────────────────────────

/// JSON serialization helpers for models.
pub trait Serializes: ModelMeta + Serialize {
    /// Convert to the public-facing struct (hidden fields excluded).
    fn to_public(&self) -> Self::Public;

    /// Serialize self to a JSON `Value`.
    fn to_json(&self) -> serde_json::Value {
        serde_json::to_value(self).unwrap_or(serde_json::Value::Null)
    }

    /// Serialize the public representation to a JSON `Value`.
    fn to_public_json(&self) -> serde_json::Value {
        serde_json::to_value(self.to_public()).unwrap_or(serde_json::Value::Null)
    }
}

// ── HasTimestamps ────────────────────────────────────────────────────────

/// Timestamp helper — touch `updated_at` on save.
///
/// Auto-implemented by `#[derive(Model)]` when timestamps are enabled.
#[async_trait::async_trait]
pub trait HasTimestamps: ActiveModelExt {
    /// Set `updated_at` to the current database time.
    async fn touch(self, db: &DatabaseConnection) -> Result<Self> {
        let data = serde_json::to_value(&self)?;
        let id_col = Self::id_column();
        let id_val = data
            .get(id_col)
            .ok_or_else(|| RavelEloquentError::Other("Cannot touch: missing id".into()))?;
        let id_sea_val = json_val_to_sea_value(id_val);

        let sql = format!(
            "UPDATE \"{}\" SET \"updated_at\" = CURRENT_TIMESTAMP WHERE \"{}\" = $1",
            Self::table_name(),
            id_col,
        );
        let stmt = Statement::from_sql_and_values(
            db.get_database_backend(), &sql, [id_sea_val]);
        db.execute(&StmtExec(stmt))
            .await
            .map_err(RavelEloquentError::Database)?;

        let id_for_fetch = json_val_to_sea_value(id_val);
        Self::find(db, id_for_fetch)
            .await?
            .ok_or_else(|| RavelEloquentError::RecordNotFound {
                table: Self::table_name(),
                id: id_val.to_string(),
            })
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────

/// Adapter: wraps a `Statement` so it implements `StatementBuilder`.
/// SeaORM 2.0-rc's `ConnectionTrait::execute()` requires `StatementBuilder`
/// but `Statement` itself doesn't implement it.  This wrapper is the
/// trivially-correct zero-cost bridge.
use sea_orm::StatementBuilder;

struct StmtExec(Statement);

impl StatementBuilder for StmtExec {
    fn build(&self, _db_backend: &sea_orm::DbBackend) -> Statement {
        self.0.clone()
    }
}

/// Convert a `serde_json::Value` to `sea_orm::Value` for use with parameterized queries.
fn json_val_to_sea_value(v: &serde_json::Value) -> Value {
    match v {
        serde_json::Value::Null => Value::BigInt(None),
        serde_json::Value::Bool(b) => Value::Bool(Some(*b)),
        serde_json::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                Value::BigInt(Some(i))
            } else if let Some(f) = n.as_f64() {
                Value::Double(Some(f))
            } else {
                Value::BigInt(None)
            }
        }
        serde_json::Value::String(s) => Value::String(Some(s.clone())),
        _ => Value::BigInt(None),
    }
}
