//! ModelQuery — fluent Eloquent-style query builder backed by SeaORM.
//!
//! Generates SQL strings and executes them via SeaORM's raw query API.

use crate::error::{RavelEloquentError, Result};
use sea_orm::{ConnectionTrait, DatabaseConnection, Statement, Value};
use serde::Serialize;
use serde::de::DeserializeOwned;
use std::fmt::Write;

// ── ModelMeta trait ────────────────────────────────────────────────

/// Metadata about a model generated by `#[derive(Model)]`.
pub trait ModelMeta {
    fn table_name() -> &'static str;
    fn columns() -> &'static [&'static str];
    fn id_column() -> &'static str;
}

// ── ModelQuery ─────────────────────────────────────────────────────

/// Fluent query builder with Laravel Eloquent-style chaining.
#[derive(Debug)]
pub struct ModelQuery<T> {
    pub(crate) table: String,
    pub(crate) wheres: Vec<(String, Value)>,
    pub(crate) orderings: Vec<(String, String)>,
    pub(crate) limit_val: Option<u64>,
    pub(crate) offset_val: Option<u64>,
    _marker: std::marker::PhantomData<T>,
}

impl<T> Clone for ModelQuery<T> {
    fn clone(&self) -> Self {
        Self {
            table: self.table.clone(),
            wheres: self.wheres.clone(),
            orderings: self.orderings.clone(),
            limit_val: self.limit_val,
            offset_val: self.offset_val,
            _marker: std::marker::PhantomData,
        }
    }
}

impl<T> ModelQuery<T> {
    pub fn new() -> Self {
        Self {
            table: String::new(),
            wheres: Vec::new(),
            orderings: Vec::new(),
            limit_val: None,
            offset_val: None,
            _marker: std::marker::PhantomData,
        }
    }

    pub fn table(mut self, name: impl Into<String>) -> Self {
        self.table = name.into();
        self
    }

    pub fn r#where(mut self, col: impl AsRef<str>, val: impl Into<Value>) -> Self {
        self.wheres.push((col.as_ref().to_string(), val.into()));
        self
    }

    pub fn order_by(mut self, col: impl AsRef<str>, dir: impl Into<String>) -> Self {
        self.orderings.push((col.as_ref().to_string(), dir.into()));
        self
    }

    pub fn limit(mut self, n: u64) -> Self {
        self.limit_val = Some(n);
        self
    }

    pub fn offset(mut self, n: u64) -> Self {
        self.offset_val = Some(n);
        self
    }

    // ── SQL generation ──────────────────────────────────────────────

    pub fn to_select_sql(&self) -> String {
        let mut sql = format!("SELECT * FROM \"{}\"", self.table);
        self.append_where(&mut sql);
        self.append_order(&mut sql);
        self.append_limit_offset(&mut sql);
        sql
    }

    pub fn to_count_sql(&self) -> String {
        let mut sql = format!("SELECT COUNT(*) as count FROM \"{}\"", self.table);
        self.append_where(&mut sql);
        sql
    }

    pub fn to_delete_sql(&self) -> String {
        let mut sql = format!("DELETE FROM \"{}\"", self.table);
        self.append_where(&mut sql);
        sql
    }

    fn append_where(&self, sql: &mut String) {
        if !self.wheres.is_empty() {
            let clauses: Vec<_> = self
                .wheres
                .iter()
                .map(|(col, val)| format!("\"{}\" = {}", col, quote_value(val)))
                .collect();
            write!(sql, " WHERE {}", clauses.join(" AND ")).unwrap();
        }
    }

    fn append_order(&self, sql: &mut String) {
        if !self.orderings.is_empty() {
            let clauses: Vec<_> = self
                .orderings
                .iter()
                .map(|(col, dir)| format!("\"{}\" {}", col, dir))
                .collect();
            write!(sql, " ORDER BY {}", clauses.join(", ")).unwrap();
        }
    }

    fn append_limit_offset(&self, sql: &mut String) {
        if let Some(n) = self.limit_val {
            write!(sql, " LIMIT {}", n).unwrap();
        }
        if let Some(n) = self.offset_val {
            write!(sql, " OFFSET {}", n).unwrap();
        }
    }

    // ── Execution ───────────────────────────────────────────────────

    /// Execute SELECT and return matching rows.
    pub async fn get(self, db: &DatabaseConnection) -> Result<Vec<T>>
    where
        T: DeserializeOwned + ModelMeta,
    {
        let sql = self.to_select_sql();
        let rows = db
            .query_all_raw(Statement::from_string(db.get_database_backend(), sql))
            .await?;
        let cols = T::columns();
        rows.into_iter().map(|r| row_to_model(&r, cols)).collect()
    }

    /// Execute SELECT and return the first matching row.
    pub async fn first(self, db: &DatabaseConnection) -> Result<Option<T>>
    where
        T: DeserializeOwned + ModelMeta,
    {
        Ok(self.limit(1).get(db).await?.into_iter().next())
    }

    /// Execute COUNT and return matching row count.
    pub async fn count(self, db: &DatabaseConnection) -> Result<u64> {
        let sql = self.to_count_sql();
        let rows = db
            .query_all_raw(Statement::from_string(db.get_database_backend(), sql))
            .await?;
        if let Some(row) = rows.into_iter().next()
            && let Ok(count) = row.try_get_by_index::<i64>(0)
        {
            return Ok(count as u64);
        }
        Ok(0)
    }

    /// Check whether any matching rows exist.
    pub async fn exists(self, db: &DatabaseConnection) -> Result<bool> {
        Ok(self.count(db).await? > 0)
    }

    /// Paginate results.
    pub async fn paginate(
        self,
        db: &DatabaseConnection,
        page: u64,
        per_page: u64,
    ) -> Result<Page<T>>
    where
        T: DeserializeOwned + ModelMeta,
    {
        let total = self.clone().count(db).await?;
        let offset = (page.saturating_sub(1)).saturating_mul(per_page);
        let items = self.offset(offset).limit(per_page).get(db).await?;
        Ok(Page::new(items, total, page.max(1), per_page))
    }

    /// Execute DELETE and return rows affected.
    pub async fn delete(self, db: &DatabaseConnection) -> Result<u64> {
        let sql = self.to_delete_sql();
        let result = db.execute_unprepared(&sql).await?;
        Ok(result.rows_affected())
    }
}

impl<T> Default for ModelQuery<T> {
    fn default() -> Self {
        Self::new()
    }
}

// ── Pagination ─────────────────────────────────────────────────────

pub type Page<T> = ravel_db_core::pagination::Page<T>;

// ── ModelExt trait ─────────────────────────────────────────────────

#[async_trait::async_trait]
pub trait ModelExt: DeserializeOwned + Serialize + Send + Sync + ModelMeta + 'static {
    async fn create(data: serde_json::Value, db: &DatabaseConnection) -> Result<Self>
    where
        Self: Sized;

    async fn update_by_id(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
        data: serde_json::Value,
    ) -> Result<()>
    where
        Self: Sized;

    async fn delete_by_id(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
    ) -> Result<()>
    where
        Self: Sized;

    async fn find(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
    ) -> Result<Option<Self>>
    where
        Self: Sized;

    async fn all(db: &DatabaseConnection) -> Result<Vec<Self>>
    where
        Self: Sized;

    async fn find_or_fail(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
    ) -> Result<Self>
    where
        Self: Sized,
    {
        let id_val: sea_orm::Value = id.into();
        let id_str = format!("{:?}", id_val);
        Self::find(db, id_val)
            .await?
            .ok_or_else(|| RavelEloquentError::RecordNotFound {
                table: Self::table_name(),
                id: id_str,
            })
    }
}

// ── Default CRUD implementations ───────────────────────────────────

pub mod defaults {
    use super::*;

    pub async fn create<T: ModelMeta + DeserializeOwned>(
        data: serde_json::Value,
        db: &DatabaseConnection,
    ) -> Result<T> {
        let cols: Vec<_> = T::columns().iter().map(|c| format!("\"{}\"", c)).collect();
        let vals: Vec<_> = T::columns()
            .iter()
            .map(|c| {
                data.get(c)
                    .map(quote_json)
                    .unwrap_or_else(|| "DEFAULT".into())
            })
            .collect();

        let sql = format!(
            "INSERT INTO \"{}\" ({}) VALUES ({}) RETURNING *",
            T::table_name(),
            cols.join(", "),
            vals.join(", ")
        );

        let rows = db
            .query_all_raw(Statement::from_string(db.get_database_backend(), sql))
            .await?;
        row_to_model(
            &rows
                .into_iter()
                .next()
                .ok_or_else(|| {
                    RavelEloquentError::Other("INSERT returned no rows".into())
                })?,
            T::columns(),
        )
    }

    pub async fn all<T: ModelMeta + DeserializeOwned>(
        db: &DatabaseConnection,
    ) -> Result<Vec<T>> {
        ModelQuery::<T>::new().table(T::table_name()).get(db).await
    }

    pub async fn find<T: ModelMeta + DeserializeOwned>(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
    ) -> Result<Option<T>> {
        ModelQuery::<T>::new()
            .table(T::table_name())
            .r#where(T::id_column(), id)
            .first(db)
            .await
    }

    pub async fn update_by_id<T: ModelMeta>(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
        data: serde_json::Value,
    ) -> Result<()> {
        let sets: Vec<_> = T::columns()
            .iter()
            .filter(|c| data.get(*c).is_some())
            .map(|c| format!("\"{}\" = {}", c, quote_json(&data[c])))
            .collect();

        if sets.is_empty() {
            return Ok(());
        }

        let sql = format!(
            "UPDATE \"{}\" SET {} WHERE \"{}\" = {}",
            T::table_name(),
            sets.join(", "),
            T::id_column(),
            quote_value(&id.into())
        );

        db.execute_unprepared(&sql).await?;
        Ok(())
    }

    pub async fn delete_by_id<T: ModelMeta>(
        db: &DatabaseConnection,
        id: impl Into<Value> + Send,
    ) -> Result<()> {
        let sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = {}",
            T::table_name(),
            T::id_column(),
            quote_value(&id.into())
        );
        db.execute_unprepared(&sql).await?;
        Ok(())
    }
}

// ── SQL helpers ────────────────────────────────────────────────────

pub(crate) fn quote_value(v: &Value) -> String {
    match v {
        Value::BigInt(Some(i)) => i.to_string(),
        Value::Int(Some(i)) => i.to_string(),
        Value::SmallInt(Some(i)) => i.to_string(),
        Value::TinyInt(Some(i)) => i.to_string(),
        Value::Float(Some(f)) => f.to_string(),
        Value::Double(Some(f)) => f.to_string(),
        Value::Bool(Some(b)) => (if *b { "TRUE" } else { "FALSE" }).to_string(),
        Value::String(Some(s)) => format!("'{}'", s.replace('\'', "''")),
        Value::Char(Some(c)) => format!("'{}'", c),
        Value::Uuid(Some(u)) => format!("'{}'", u),
        Value::ChronoDate(Some(d)) => format!("'{}'", d),
        Value::ChronoDateTime(Some(dt)) => format!("'{}'", dt),
        Value::ChronoDateTimeUtc(Some(dt)) => format!("'{}'", dt),
        Value::Decimal(Some(d)) => format!("'{}'", d),
        Value::BigUnsigned(Some(u)) => u.to_string(),
        Value::Unsigned(Some(u)) => u.to_string(),
        _ => "NULL".to_string(),
    }
}

fn quote_json(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::Null => "NULL".to_string(),
        serde_json::Value::Bool(b) => (if *b { "TRUE" } else { "FALSE" }).to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => format!("'{}'", s.replace('\'', "''")),
        _ => format!("'{}'", v),
    }
}

pub(crate) fn row_to_model<T: DeserializeOwned>(
    row: &sea_orm::QueryResult,
    cols: &[&str],
) -> Result<T> {
    let mut map = serde_json::Map::new();
    for (i, col) in cols.iter().enumerate() {
        let val = try_extract(row, i);
        map.insert(col.to_string(), val);
    }
    Ok(serde_json::from_value(serde_json::Value::Object(map))?)
}

fn try_extract(row: &sea_orm::QueryResult, index: usize) -> serde_json::Value {
    if let Ok(v) = row.try_get_by_index::<String>(index) {
        serde_json::Value::String(v)
    } else if let Ok(v) = row.try_get_by_index::<i64>(index) {
        serde_json::json!(v)
    } else if let Ok(v) = row.try_get_by_index::<i32>(index) {
        serde_json::json!(v)
    } else if let Ok(v) = row.try_get_by_index::<f64>(index) {
        serde_json::json!(v)
    } else if let Ok(v) = row.try_get_by_index::<bool>(index) {
        serde_json::json!(v)
    } else {
        serde_json::Value::Null
    }
}
